### ISSUE TITLE
Kontaktdaten

### ISSUE THREAD

**Issue by juzzeecki** [Stefanqn/Bewerbung#24]
Guten Tag, gibt es eine Möglichkeit, Sie zu kontaktieren? Das wäre sehr hilfreich, es geht um eine dringende Angelegenheit. Beste Grüße

**Comment by Stefanqn** [comment]
Moin, worum geht es?

**Comment by juzzeecki** [comment]
Hi, es geht um die Entfernung von Daten von gestern aus dem Repository. Ich schätze, als Admin ist das hoffentlich möglich.

**Comment by Stefanqn** [comment]
Welche Daten? Du dürftest hier nicht schreiben können.

**Comment by unknownFalleN** [comment]
https://github.com/Stefanqn/Bewerbung/pull/23 er meint den Pull Request, wo er seine ganzen privaten Daten gepusht hat.

**Comment by Stefanqn** [comment]
[geht nicht](https://stackoverflow.com/a/18318431).

**Comment by Stefanqn** [comment]
[geht nicht](https://stackoverflow.com/a/18318431) ohne github support request.

**Comment by juzzeecki** [comment]
"The automated system will only allow deletion if you're an admin of the repository."

Ich habe bereits eine Support Request gestellt, woraufhin mir gesagt wurde, es müsse an den Admin weitergeleitet werden.

**Comment by juzzeecki** [comment]
https://docs.github.com/de/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

Darauf wird verwiesen, wenn man Besitzer ist.

**Comment by Stefanqn** [comment]
> https://docs.github.com/de/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository
> 
> Darauf wird verwiesen, wenn man Besitzer ist.

die Daten liegen nicht in diesem Repo.

**Comment by juzzeecki** [comment]
Kannst du mir da bitte behilflich sein? Vielleicht geht es hierüber: 

https://support.github.com/contact?flow=pr_removal&subject=Delete%20Pull%20Request&tags=rr-remove-data

Mit dem Link https://github.com/Stefanqn/Bewerbung/pull/23

**Comment by Stefanqn** [comment]
============= A =============

### Transcript:
- **from_agent**: Hi, @Stefanqn.
- **from_agent**: Are you looking to remove a single pull request, or multiple pull requests?  Single Multiple
- **from_user**: *Single*
- **from_agent**: What is the URL of the pull request you'd like to remove?
- **from_user**: *https://github.com/Stefanqn/Bewerbung/pull/23*
- **from_agent**: Thanks! Validating, please wait...
- **from_agent**: Are you looking to remove the sensitive data from stefanqn/bewerbung?  Yes No
- **from_user**: *No*
- **from_agent**: We can only queue up deleting pull requests that contain sensitive data in cases where we determine that the risk can't be mitigated by rotating affected credentials.  Restart Cancel

============= B =============
### Transcript:
- **from_agent**: Hi, @Stefanqn.
- **from_agent**: Are you looking to remove a single pull request, or multiple pull requests?  Single Multiple
- **from_user**: *Single*
- **from_agent**: What is the URL of the pull request you'd like to remove?
- **from_user**: *https://github.com/Stefanqn/Bewerbung/pull/23*
- **from_agent**: It looks like this repository is not hosted on GitHub.com. Would you like to see instructions for removing sensitive data on GitHub Enterprise Server?  Show instructions No thanks

**Comment by juzzeecki** [comment]
Eigentlich sah das in Transkript A doch passend aus, oder? Warum "No" bei removal of sensitive data? Das wäre doch genau das, oder?

**Comment by Stefanqn** [comment]
ja, das wählte ich beim ersten Mal (vor A). Der Dialog geht dort nicht mehr hin (B)

**Comment by juzzeecki** [comment]
Auch nicht mehr, wenn man den Prozess neu startet? 
Vielleicht wäre es ansonsten möglich, die Support Request auszufüllen? 
https://support.github.com/contact/private-information
Als Besitzer des Repos könnte es dann ja funktionieren. Ich wäre sehr dankbar, wenn eine der Möglichkeiten funktioniert!

**Comment by Stefanqn** [comment]
Hi, @Stefanqn.
Virtual Assistant avatar

Are you looking to remove a single pull request, or multiple pull requests?
Virtual Assistant avatar
Single
Virtual Assistant avatar

What is the URL of the pull request you'd like to remove?
Virtual Assistant avatar
https://github.com/Stefanqn/Bewerbung/pull/23
Virtual Assistant avatar

Thanks! Validating, please wait...
Virtual Assistant avatar

Are you looking to remove the sensitive data from stefanqn/bewerbung?
Virtual Assistant avatar
Yes
Virtual Assistant avatar

Have you removed the sensitive data from the git history of stefanqn/bewerbung? Has the affected sensitive data also been rotated or expired?
Virtual Assistant avatar
No
Virtual Assistant avatar

You can remove the file from the history by following [our guide](https://docs.github.com/github/authenticating-to-github/removing-sensitive-data-from-a-repository)
Virtual Assistant avatar
Removed sensitive data
Virtual Assistant avatar

Have you removed the sensitive data from the git history of stefanqn/bewerbung? Has the affected sensitive data also been rotated or expired?
Virtual Assistant avatar
Yes
Virtual Assistant avatar

Has this resolved your issue? Is this not a case where the risk can't be mitigated by rotating affected credentials so that the pull request(s) can remain?
Virtual Assistant avatar
No
Virtual Assistant avatar

Please share why the issue isn't resolved or the Pull Requests need to be deleted.
Virtual Assistant avatar
Pull Requests contains cached sensitive data
Virtual Assistant avatar

Creating a ticket for your request...
Virtual Assistant avatar

Ticket created, we'll update you when we've removed the noted Pull Request.
Virtual Assistant avatar

All done. Thank you for using Virtual Assistant.
Virtual Assistant avatar

Did this help you?
Virtual Assistant avatar
Yes
Virtual Assistant avatar

That's great to hear.
Virtual Assistant avatar

Submitting your survey response...
Virtual Assistant avatar

All done. Thank you for your feedback.
Virtual Assistant avatar

Have a great day!

**Comment by Stefanqn** [comment]
ansonsten
> You cannot remove sensitive data from other users' clones of your repository, but you can permanently remove cached views and references to the sensitive data in pull requests on GitHub by contacting us through the [GitHub Support portal](https://support.github.com/).

[About sensitive data exposure](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#about-sensitive-data-exposure)

**Comment by juzzeecki** [comment]
Danke dir, mal sehen ob das was wird. Ich habe schon mehrere support requests & mails abgesendet, bei der einen, die bis jetzt zurück kam, wurde primär gesagt, ich müsse mich an den owner wenden. Danke.

**Comment by Stefanqn** [comment]
> Hi Stefanqn,
>  
> No problem! I've deleted that pull request and cleared out unreferenced commits.
>  
> Of course, we still recommend changing any leaked credentials as soon as possible, if you haven't already.
>  
> Feel free to reach out again if you need anything else!
> 
> Kind regards,
> Lauren

https://support.github.com/ticket/3082670

**Comment by juzzeecki** [comment]
Ich danke dir sehr!
